export const LOAD_FEED_START= 'LOAD_FEED_START';
export const LOAD_FEED_SUCCESS= 'LOAD_FEED_SUCCESS';
export const LOAD_FEED_ERROR= 'LOAD_FEED_ERROR';

export const LOAD_VIDEOPAGE_START= 'LOAD_VIDEOPAGE_START';
export const LOAD_VIDEOPAGE_SUCCESS= 'LOAD_VIDEOPAGE_SUCCESS';
export const LOAD_VIDEOPAGE_ERROR= 'LOAD_VIDEOPAGE_ERROR';